# Generated by Django 4.0.3 on 2022-05-05 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='desription',
            new_name='description',
        ),
    ]
