# Generated by Django 4.0.3 on 2022-04-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='THUMB',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
