# Generated by Django 4.0.3 on 2022-04-11 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_thumb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='THUMB',
            new_name='thumb',
        ),
    ]
